import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../services/race_intelligence_service.dart';

/// One-page Meet-Day Brief from Race Intelligence.
class MeetDayBriefPdf {
  MeetDayBriefPdf._();

  static Future<List<int>> buildBytes({
    required RaceIntelligencePlan plan,
    required String athleteName,
  }) async {
    final doc = pw.Document();
    final meetTitle = plan.meetTitle?.trim().isNotEmpty == true
        ? plan.meetTitle!.trim()
        : plan.meetDayLabel;

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(36),
        build: (context) => [
          pw.Text(
            'SWIMIQ MEET-DAY BRIEF',
            style: pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey700,
              letterSpacing: 1.1,
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            athleteName.toUpperCase(),
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blue900,
            ),
          ),
          pw.Text(
            _pdfSafe(
              plan.syncedToSchedule
                  ? 'Synced to $meetTitle'
                  : 'General race-day plan (add meet on Log -> Meets to sync)',
            ),
            style: const pw.TextStyle(fontSize: 11),
          ),
          if (plan.meetStartTime?.trim().isNotEmpty == true ||
              plan.meetLocation?.trim().isNotEmpty == true)
            pw.Text(
              [
                if (plan.meetStartTime?.trim().isNotEmpty == true)
                  plan.meetStartTime!.trim(),
                if (plan.meetLocation?.trim().isNotEmpty == true)
                  plan.meetLocation!.trim(),
              ].join(' | '),
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
            ),
          pw.SizedBox(height: 6),
          pw.Divider(thickness: 2, color: PdfColors.blue800),
          _section('Focus event', [
            pw.Text(
              plan.focusEvent,
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
            if (plan.meetEvents.length > 1)
              pw.Text(
                'Also swimming: ${plan.meetEvents.where((e) => e != plan.focusEvent).join(', ')}',
                style: const pw.TextStyle(fontSize: 9),
              ),
          ]),
          _section('Meet-day timeline', [
            ...plan.timeline.map(
              (step) => pw.Bullet(
                text: _pdfSafe('${step.label}: ${step.detail}'),
              ),
            ),
          ]),
          _section('Midday checklist', [
            ...plan.middayChecklist.map(
              (item) => pw.Bullet(
                text: _pdfSafe(
                  '${item.title} (${item.timingHint}) - ${item.detail}',
                ),
              ),
            ),
          ]),
          _section('Warm-up phases', [
            ...plan.warmUpPhases.map(
              (phase) => pw.Bullet(
                text: _pdfSafe(
                  'Phase ${phase.phaseNumber}: ${phase.title} '
                  '(${phase.duration}) - ${phase.detail}',
                ),
              ),
            ),
          ]),
          _section('Nutrition', [
            ...plan.nutritionPlan.map(
              (block) => pw.Bullet(
                text: _pdfSafe(
                  '${block.mealLabel} (${block.timing}): '
                  '${block.suggestions.join('; ')}. Avoid: ${block.avoid}',
                ),
              ),
            ),
          ]),
          _section('Hydration', [
            pw.Text(_pdfSafe(plan.hydrationNotes)),
          ]),
          pw.SizedBox(height: 14),
          pw.Text(
            'Generated by SwimIQ Race Intelligence - swimiqapp.com',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    return doc.save();
  }

  static String _pdfSafe(String text) => text
      .replaceAll('→', '->')
      .replaceAll('—', '-')
      .replaceAll('–', '-')
      .replaceAll('·', '-')
      .replaceAll('’', "'")
      .replaceAll('‘', "'");

  static pw.Widget _section(String title, List<pw.Widget> children) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(height: 10),
        pw.Text(
          title.toUpperCase(),
          style: pw.TextStyle(
            fontSize: 11,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.blue800,
          ),
        ),
        pw.SizedBox(height: 4),
        ...children,
      ],
    );
  }
}
