import '../../data/models/personal_best_entry.dart';
import '../../data/models/swimmer_profile.dart';
import '../utils/swim_time.dart';

/// Builds a one-page recruiting résumé from passport + performance data.
class RecruitingResumeBuilder {
  RecruitingResumeBuilder._();

  static String buildText({
    required SwimmerProfile? profile,
    required String displayName,
    required List<PersonalBestEntry> personalBests,
    required int swimIqScore,
    required String highestCut,
    required List<String> championshipsQualified,
    String? powerIndexLine,
  }) {
    final buffer = StringBuffer();
    final name = profile?.displayName ?? displayName;

    buffer.writeln('SWIMIQ RECRUITING RÉSUMÉ');
    buffer.writeln('═' * 40);
    buffer.writeln(name.toUpperCase());
    buffer.writeln();

    _section(buffer, 'Athlete Profile');
    _line(buffer, 'Graduation', profile?.graduationYear?.toString());
    _line(buffer, 'Recruiting status', profile?.recruitingStatus);
    _line(buffer, 'Club team', profile?.team);
    _line(buffer, 'High school', profile?.school);
    _line(buffer, 'Coach', profile?.coachName);
    _line(buffer, 'Coach email', profile?.coachEmail);
    _line(buffer, 'Coach phone', profile?.coachPhone);
    _line(buffer, 'Athlete email', profile?.athleteEmail ?? profile?.recruitingEmail);
    _line(buffer, 'Athlete phone', profile?.athletePhone);
    _line(buffer, 'Website', profile?.athleteWebsite);
    _line(buffer, 'USA Swimming ID', profile?.usaSwimmingId);
    _line(buffer, 'Primary stroke', profile?.primaryStroke);
    _line(buffer, 'Favorite event', profile?.favoriteEvent);
    buffer.writeln();

    _section(buffer, 'Academics');
    _line(buffer, 'GPA', profile?.gpa);
    _line(buffer, 'SAT', profile?.satScore);
    _line(buffer, 'ACT', profile?.actScore);
    _line(buffer, 'Intended major', profile?.intendedMajor);
    _line(buffer, 'Academic honors', profile?.academicHonors);
    buffer.writeln();

    _section(buffer, 'Top Times');
    if (personalBests.isEmpty) {
      buffer.writeln('No official times logged yet.');
    } else {
      for (final pb in personalBests.take(8)) {
        buffer.writeln(
          '  • ${pb.displayTitle} (${pb.course}): ${pb.formattedTime}',
        );
      }
    }
    buffer.writeln();

    _section(buffer, 'Performance Snapshot');
    _line(buffer, 'SwimIQ Score', swimIqScore > 0 ? '$swimIqScore' : null);
    _line(buffer, 'Highest USA cut', highestCut);
    _line(
      buffer,
      'Power Index',
      (powerIndexLine != null && powerIndexLine.trim().isNotEmpty)
          ? powerIndexLine
          : 'Add official PBs and birthday/gender to calculate',
    );
    buffer.writeln();

    _section(buffer, 'Awards & Honors');
    _line(buffer, 'Athletic honors', profile?.athleticHonors);
    if (championshipsQualified.isEmpty) {
      buffer.writeln('  • Log meet results to track championship qualifications');
    } else {
      for (final item in championshipsQualified) {
        buffer.writeln('  • $item');
      }
    }
    buffer.writeln();

    _section(buffer, 'Leadership & Activities');
    _line(buffer, 'Leadership & service', profile?.leadershipService);
    _line(buffer, 'Other interests', profile?.otherInterests);
    _line(buffer, 'College interests', profile?.collegeInterests);
    buffer.writeln();

    buffer.writeln('Generated by SwimIQ · swimiqapp.com');
    return buffer.toString();
  }

  static List<String> championshipTags({
    required String highestCut,
    required List<PersonalBestEntry> personalBests,
  }) {
    final tags = <String>[];
    if (highestCut.isNotEmpty &&
        highestCut != 'No motivational cut matched yet' &&
        highestCut != 'Log sessions to compare against cuts') {
      tags.add('USA Swimming $highestCut motivational standard');
    }
    for (final pb in personalBests.take(3)) {
      tags.add('${pb.displayTitle} — ${SwimTime.fromSeconds(pb.timeSeconds)} (${pb.course})');
    }
    return tags;
  }

  static void _section(StringBuffer buffer, String title) {
    buffer.writeln(title.toUpperCase());
    buffer.writeln('─' * title.length);
  }

  static void _line(StringBuffer buffer, String label, String? value) {
    final text = value?.trim();
    if (text == null || text.isEmpty) return;
    buffer.writeln('$label: $text');
  }
}
