import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../data/models/personal_best_entry.dart';
import '../../data/models/swimmer_profile.dart';

/// Builds a one-page PDF recruiting résumé for export/share.
class RecruitingResumePdf {
  RecruitingResumePdf._();

  static Future<List<int>> buildBytes({
    required SwimmerProfile? profile,
    required String displayName,
    required List<PersonalBestEntry> personalBests,
    required int swimIqScore,
    required String highestCut,
    required List<String> championshipsQualified,
    String? powerIndexLine,
  }) async {
    final doc = pw.Document();
    final name = profile?.displayName ?? displayName;

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          pw.Text(
            'SWIMIQ RECRUITING RÉSUMÉ',
            style: pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey700,
              letterSpacing: 1.2,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            name.toUpperCase(),
            style: pw.TextStyle(
              fontSize: 22,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.Divider(thickness: 2),
          pw.SizedBox(height: 8),
          _section('Athlete Profile', [
            _line('Class of', profile?.graduationYear?.toString()),
            _line('Recruiting status', profile?.recruitingStatus),
            _line('Club team', profile?.team),
            _line('High school', profile?.school),
            _line('Coach', profile?.coachName),
            _line('Coach contact', profile?.coachEmail),
            _line(
              'Athlete email',
              profile?.athleteEmail ?? profile?.recruitingEmail,
            ),
            _line('USA Swimming ID', profile?.usaSwimmingId),
            _line('Primary stroke', profile?.primaryStroke),
            _line('Favorite event', profile?.favoriteEvent),
          ]),
          _section('Academics', [
            _line('GPA', profile?.gpa),
            _line('SAT', profile?.satScore),
            _line('ACT', profile?.actScore),
            _line('Intended major', profile?.intendedMajor),
            _line('Academic honors', profile?.academicHonors),
          ]),
          _section('Top Times', [
            if (personalBests.isEmpty)
              pw.Text('No official times logged yet.')
            else
              ...personalBests.take(8).map(
                    (pb) => pw.Bullet(
                      text:
                          '${pb.displayTitle} (${pb.course}): ${pb.formattedTime}',
                    ),
                  ),
          ]),
          _section('Performance Snapshot', [
            if (swimIqScore > 0)
              pw.Text('SwimIQ Score: $swimIqScore')
            else
              pw.Text('SwimIQ Score: not yet calculated'),
            pw.Text('Highest USA cut: $highestCut'),
            pw.Text(
              'Power Index: ${powerIndexLine?.trim().isNotEmpty == true ? powerIndexLine : 'Add official PBs and birthday/gender to calculate'}',
            ),
          ]),
          _section('Awards & Honors', [
            if (profile?.athleticHonors != null)
              pw.Text('Athletic: ${profile!.athleticHonors}'),
            if (championshipsQualified.isEmpty)
              pw.Text('Log meet results to track championship qualifications.')
            else
              ...championshipsQualified.map((c) => pw.Bullet(text: c)),
          ]),
          _section('Leadership & Activities', [
            if (profile?.leadershipService != null)
              pw.Text(profile!.leadershipService!),
            if (profile?.collegeInterests != null)
              pw.Text('College interests: ${profile!.collegeInterests}'),
            if (profile?.athleteWebsite != null)
              pw.Text('Website: ${profile!.athleteWebsite}'),
          ]),
          pw.Spacer(),
          pw.Text(
            'Generated by SwimIQ · swimiqapp.com',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _section(String title, List<pw.Widget> children) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(height: 10),
        pw.Text(
          title.toUpperCase(),
          style: pw.TextStyle(
            fontSize: 11,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.blue800,
          ),
        ),
        pw.SizedBox(height: 4),
        ...children,
      ],
    );
  }

  static pw.Widget _line(String label, String? value) {
    final text = value?.trim();
    if (text == null || text.isEmpty) return pw.SizedBox();
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 2),
      child: pw.Text('$label: $text', style: const pw.TextStyle(fontSize: 10)),
    );
  }
}
