-- SwimIQ V1 extension: video upload, AI analysis, USA standards
-- Run this in Supabase Dashboard → SQL Editor

CREATE TABLE IF NOT EXISTS public.swim_videos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  swimmer_name text NOT NULL,
  title text,
  stroke text,
  distance integer,
  course text,
  storage_path text NOT NULL,
  video_url text,
  notes text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.swim_video_analyses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  swim_video_id bigint REFERENCES public.swim_videos(id) ON DELETE CASCADE,
  swimmer_name text NOT NULL,
  summary text,
  strengths text,
  improvements text,
  technique_score integer,
  pace_score integer,
  overall_score integer,
  analysis_json jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.usa_time_standards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  age_group text NOT NULL,
  gender text NOT NULL,
  stroke text NOT NULL,
  distance integer NOT NULL,
  course text NOT NULL,
  standard_level text NOT NULL,
  time_seconds numeric NOT NULL,
  UNIQUE (age_group, gender, stroke, distance, course, standard_level)
);

ALTER TABLE public.swim_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swim_video_analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usa_time_standards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "swim_videos_all" ON public.swim_videos
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "swim_video_analyses_all" ON public.swim_video_analyses
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "usa_time_standards_all" ON public.usa_time_standards
  FOR ALL USING (true) WITH CHECK (true);

-- Storage: create bucket "swim-videos" in Dashboard → Storage (public read recommended for V1)
