-- SwimIQ: enable upcoming meet / schedule saves (Log → Meets)
-- Run once in Supabase → SQL Editor → Run
-- Project: bryurwyeosbffvfpdpbv

CREATE TABLE IF NOT EXISTS public.swim_schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  swimmer_name text NOT NULL,
  schedule_type text NOT NULL CHECK (
    schedule_type IN ('practice', 'meet', 'race')
  ),
  title text NOT NULL,
  schedule_date date NOT NULL,
  start_time text,
  location text,
  events_line text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS swim_schedules_swimmer_date_idx
  ON public.swim_schedules (swimmer_name, schedule_date DESC);

ALTER TABLE public.swim_schedules ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'swim_schedules'
      AND policyname = 'swim_schedules_all'
  ) THEN
    CREATE POLICY "swim_schedules_all" ON public.swim_schedules
      FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
